use_frameworks!
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
target 'JZStar'

pod 'Alamofire', '~> 4.8'
pod 'SwiftyJSON', '~> 4.0'

#private_project_need
pod 'SnapKit'
pod 'SwiftRichString', '~> 3.5.1'
pod 'RxSwift', '5.1.1'
pod 'RxCocoa', '5.1.1'
pod 'NSHash'
pod 'MBProgressHUD'
pod 'IQKeyboardManagerSwift'
pod 'LTMorphingLabel', '0.8.0'
pod 'pop'
pod 'FDFullscreenPopGesture', '1.1'
pod 'MJRefresh', '~> 3.2.3'
pod 'RxDataSources', '~> 4.0'
pod 'NVActivityIndicatorView'
pod 'SwipeCellKit'
pod 'TZImagePickerController' , '3.3.2'
pod 'Kingfisher', '5.14.0'
pod 'CountryPickerView', '3.1.2'
pod 'libPhoneNumber-iOS'
pod 'CryptoSwift', '1.3.1'
pod 'KakaJSON', '~> 1.1.2'
pod 'Moya', '~> 13.0.1'
pod 'FSPagerView'



