$axure.loadCurrentPage({
  "url":"客服中心.html",
  "generationDate":new Date(1590810246404.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b2475791ee23489b9d507616888053b9",
    "type":"Axure:Page",
    "name":"客服中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b16958a1f83646ca8aeb01ce8dbebe7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":440,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17ad09f9ecb34b218b9742b6fbeb6f9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":440,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u0.png"}},
{
          "id":"ac4628878bbc4142b7cfa6c45d9db1f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":50},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e60b93c7fc50470f86a17b7e849b7a65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":50},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"418290d17c69430ab05cc7e979cca689",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":62},
            "size":{
              "width":130,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acfe500748384b1e94443e3de9e97086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":62},
                "size":{
                  "width":130,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0aab27fc9644a659baee62ac366cd20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":72},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8360b5479c848079d030617078d4235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":72},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dadaf1f17a24995a6dc3d00fd38ddaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":140},
            "size":{
              "width":280,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43b1b98d54af49c6922b2c42ae0020c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":140},
                "size":{
                  "width":280,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服中心/u8.png"}},
{
          "id":"a03a3eec228c4ec18d546f53374fd204",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":140},
            "size":{
              "width":50,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b57506df385b45ff8de081644bb2b7fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":140},
                "size":{
                  "width":50,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服中心/u10.png"}},
{
          "id":"307aff96c416476ca37838623fee95b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":146},
            "size":{
              "width":260,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2778eba63e694c81b0254137c3847977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":146},
                "size":{
                  "width":260,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a58610829a764e42a956284c433ac238",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":390},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eea079ce9ce24f288051703b8e24fc70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":390},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服中心/u14.png"}},
{
          "id":"75c0a110ee4e435ea6c425924d6531ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":390},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4a23fbb01bf4732862cb5633d43bd8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":390},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服中心/u16.png"}},
{
          "id":"46458de92a864d06a4dbc2820e3bcf34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":407},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fccf9ec499b43e1bbae06a1392556a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":407},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32835facd6d04a30881333bce47cd89e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":515},
            "size":{
              "width":50,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c58a9e07f20544a79f3b3204e90271f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":515},
                "size":{
                  "width":50,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服中心/u10.png"}},
{
          "id":"7a71f54bc3664173a83527af5048bb3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":515},
            "size":{
              "width":280,
              "height":205}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb39b35d767e4ce9affbc3c4abb328c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":515},
                "size":{
                  "width":280,
                  "height":205}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服中心/u22.png"}},
{
          "id":"f916bd60d2164d8abdd2643977b32a8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":526},
            "size":{
              "width":260,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5d904e595524baeb3930b6c5ab70ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":526},
                "size":{
                  "width":260,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d66c9f6c949c4b6db1c58498f715a4e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":60},
            "size":{
              "width":352,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a95ba7dfac534296a20d90d7fa1b20dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":60},
                "size":{
                  "width":352,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘信息详情/u21.png"}},
{
          "id":"17e3611c65304e13b1f38e3bd961dd10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"32px",
            "fontWeight":"700",
            "location":{
              "x":620,
              "y":73},
            "size":{
              "width":200,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11e8cb78847944f78c92686744fea18a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"32px",
                "fontWeight":"700",
                "location":{
                  "x":620,
                  "y":73},
                "size":{
                  "width":200,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e8b2a1d6a594bd9ab2a26d7c58a7dbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":130},
            "size":{
              "width":300,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b3831f74837433e83c5378ca4778d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":130},
                "size":{
                  "width":300,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b16958a1f83646ca8aeb01ce8dbebe7d":{
      "scriptId":"u0"},
    "17ad09f9ecb34b218b9742b6fbeb6f9e":{
      "scriptId":"u1"},
    "ac4628878bbc4142b7cfa6c45d9db1f6":{
      "scriptId":"u2"},
    "e60b93c7fc50470f86a17b7e849b7a65":{
      "scriptId":"u3"},
    "418290d17c69430ab05cc7e979cca689":{
      "scriptId":"u4"},
    "acfe500748384b1e94443e3de9e97086":{
      "scriptId":"u5"},
    "b0aab27fc9644a659baee62ac366cd20":{
      "scriptId":"u6"},
    "a8360b5479c848079d030617078d4235":{
      "scriptId":"u7"},
    "8dadaf1f17a24995a6dc3d00fd38ddaa":{
      "scriptId":"u8"},
    "43b1b98d54af49c6922b2c42ae0020c1":{
      "scriptId":"u9"},
    "a03a3eec228c4ec18d546f53374fd204":{
      "scriptId":"u10"},
    "b57506df385b45ff8de081644bb2b7fe":{
      "scriptId":"u11"},
    "307aff96c416476ca37838623fee95b0":{
      "scriptId":"u12"},
    "2778eba63e694c81b0254137c3847977":{
      "scriptId":"u13"},
    "a58610829a764e42a956284c433ac238":{
      "scriptId":"u14"},
    "eea079ce9ce24f288051703b8e24fc70":{
      "scriptId":"u15"},
    "75c0a110ee4e435ea6c425924d6531ec":{
      "scriptId":"u16"},
    "e4a23fbb01bf4732862cb5633d43bd8d":{
      "scriptId":"u17"},
    "46458de92a864d06a4dbc2820e3bcf34":{
      "scriptId":"u18"},
    "8fccf9ec499b43e1bbae06a1392556a8":{
      "scriptId":"u19"},
    "32835facd6d04a30881333bce47cd89e":{
      "scriptId":"u20"},
    "c58a9e07f20544a79f3b3204e90271f1":{
      "scriptId":"u21"},
    "7a71f54bc3664173a83527af5048bb3a":{
      "scriptId":"u22"},
    "eb39b35d767e4ce9affbc3c4abb328c0":{
      "scriptId":"u23"},
    "f916bd60d2164d8abdd2643977b32a8a":{
      "scriptId":"u24"},
    "d5d904e595524baeb3930b6c5ab70ef6":{
      "scriptId":"u25"},
    "d66c9f6c949c4b6db1c58498f715a4e2":{
      "scriptId":"u26"},
    "a95ba7dfac534296a20d90d7fa1b20dd":{
      "scriptId":"u27"},
    "17e3611c65304e13b1f38e3bd961dd10":{
      "scriptId":"u28"},
    "11e8cb78847944f78c92686744fea18a":{
      "scriptId":"u29"},
    "7e8b2a1d6a594bd9ab2a26d7c58a7dbb":{
      "scriptId":"u30"},
    "5b3831f74837433e83c5378ca4778d03":{
      "scriptId":"u31"}}});