$axure.loadCurrentPage({
  "url":"意见投诉.html",
  "generationDate":new Date(1590810246490.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f413ca44dffc4c37854e28e2389f812d",
    "type":"Axure:Page",
    "name":"意见投诉",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"424898cd7d1744a6ab9d212fe863f1ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":440,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ccc828f59ab4ff0bd11352fe9df8805",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":440,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u0.png"}},
{
          "id":"9ebb3933758d43199f0d77f9f4935569",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":50},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"465216c964724523aaa9052951696b8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":50},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"f21a5309ab9f40bdb1154bc7b482f3f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":62},
            "size":{
              "width":130,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f24dbe1741d546028f300e08fc9c6234",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":62},
                "size":{
                  "width":130,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc234c4ed3ee4a50aeefb6b7d7c048f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":72},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f0c86621244cbeaa5449587db1c889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":72},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d0ef6c985574e228b8275e6198a17f6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":160},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"cf18d19274ec4d69aa0aca0bf1057b95",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":400,
              "height":310}},
          "adaptiveStyles":{
}},
{
          "id":"c749023927a44c4ca2354b974e98e5e1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":535},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "424898cd7d1744a6ab9d212fe863f1ce":{
      "scriptId":"u0"},
    "4ccc828f59ab4ff0bd11352fe9df8805":{
      "scriptId":"u1"},
    "9ebb3933758d43199f0d77f9f4935569":{
      "scriptId":"u2"},
    "465216c964724523aaa9052951696b8f":{
      "scriptId":"u3"},
    "f21a5309ab9f40bdb1154bc7b482f3f4":{
      "scriptId":"u4"},
    "f24dbe1741d546028f300e08fc9c6234":{
      "scriptId":"u5"},
    "fc234c4ed3ee4a50aeefb6b7d7c048f0":{
      "scriptId":"u6"},
    "c9f0c86621244cbeaa5449587db1c889":{
      "scriptId":"u7"},
    "8d0ef6c985574e228b8275e6198a17f6":{
      "scriptId":"u8"},
    "cf18d19274ec4d69aa0aca0bf1057b95":{
      "scriptId":"u9"},
    "c749023927a44c4ca2354b974e98e5e1":{
      "scriptId":"u10"}}});