$axure.loadCurrentPage({
  "url":"我的职位.html",
  "generationDate":new Date(1590810246469.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a7099c3397b240b9aaa64bdacbdf675d",
    "type":"Axure:Page",
    "name":"我的职位",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9a625386ae0e49a691fd26ac9f213997",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":440,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e5225429f74b50ab19fa413ad60356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":440,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u0.png"}},
{
          "id":"7d0784d91d624ebdaf09ef8af2d09081",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":750},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b09cb642daf14c46acc12a64d592675f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":750},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"ba1c4dbf7ee643319c100590af618818",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":772},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb73c0d080554b8e8574104e43a270cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":772},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 首页 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e94621c67e45473eb9d89df9bf545c00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":772},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"208e72599c3f482b9a38e957268e13fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":772},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 推荐首页 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"推荐首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efd33e0e806845bf83148219ad80c3d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":772},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e6383149b54ad4a257427db2aa34f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":772},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58bdd1f8f09b4c75b9f633e1605a2e71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":50},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7de770bf71e444c485dd6e8588d8d8e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":50},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"ffc63e278996465cb3c8aa07636b05e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":62},
            "size":{
              "width":130,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6559eb93e804f8e91cd09fbc35dfbf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":62},
                "size":{
                  "width":130,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b09fff9c45f4cd6ae817869f215ecd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":150},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f44e95f86894b969601f82a01ee668f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":150},
                "size":{
                  "width":90,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的职位/u14.png"}},
{
          "id":"25c840ebfa5343e68ee7f04bed8f16c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":150},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b47d97bdc74d52bb5d8c1b8171f7a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":150},
                "size":{
                  "width":90,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的职位/u14.png"}},
{
          "id":"1f0ff5b317534f3194fefd72e75a4bcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":150},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fce4cca6e9cc42f28df5a92293acb569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":150},
                "size":{
                  "width":90,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的职位/u14.png"}},
{
          "id":"ca5aebe1a1ca42a3acaeaee706ce1007",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":150},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d72ce9fd425473a839911e84c6d1286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":150},
                "size":{
                  "width":90,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的职位/u14.png"}},
{
          "id":"91504088410d479fb5c9a90a36219e7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":200},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea294d6024904b828c6a17e38ce4ee72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":200},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 招聘信息详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"招聘信息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"d604b13157b3498fb1a99496618cb54b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":300},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba1cf3b37b184737baf635ece6abcbeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":300},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 招聘信息详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"招聘信息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"3e3f630f3591482db4dd822dcf37e0d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":500},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e65e5024100c4b599ffca922e266f189",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":500},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"024c7b6c7ee345f9bf1a9a52e70dea43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":400},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccf5351c51434c41aa4a2be33b2b8bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":400},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"53214c10e57047c6b0232268cead1276",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":72},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c36511335a5451b90f12359fb90d270",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":72},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9a625386ae0e49a691fd26ac9f213997":{
      "scriptId":"u0"},
    "59e5225429f74b50ab19fa413ad60356":{
      "scriptId":"u1"},
    "7d0784d91d624ebdaf09ef8af2d09081":{
      "scriptId":"u2"},
    "b09cb642daf14c46acc12a64d592675f":{
      "scriptId":"u3"},
    "ba1c4dbf7ee643319c100590af618818":{
      "scriptId":"u4"},
    "eb73c0d080554b8e8574104e43a270cd":{
      "scriptId":"u5"},
    "e94621c67e45473eb9d89df9bf545c00":{
      "scriptId":"u6"},
    "208e72599c3f482b9a38e957268e13fb":{
      "scriptId":"u7"},
    "efd33e0e806845bf83148219ad80c3d5":{
      "scriptId":"u8"},
    "e0e6383149b54ad4a257427db2aa34f7":{
      "scriptId":"u9"},
    "58bdd1f8f09b4c75b9f633e1605a2e71":{
      "scriptId":"u10"},
    "7de770bf71e444c485dd6e8588d8d8e9":{
      "scriptId":"u11"},
    "ffc63e278996465cb3c8aa07636b05e7":{
      "scriptId":"u12"},
    "a6559eb93e804f8e91cd09fbc35dfbf2":{
      "scriptId":"u13"},
    "8b09fff9c45f4cd6ae817869f215ecd0":{
      "scriptId":"u14"},
    "6f44e95f86894b969601f82a01ee668f":{
      "scriptId":"u15"},
    "25c840ebfa5343e68ee7f04bed8f16c7":{
      "scriptId":"u16"},
    "66b47d97bdc74d52bb5d8c1b8171f7a4":{
      "scriptId":"u17"},
    "1f0ff5b317534f3194fefd72e75a4bcc":{
      "scriptId":"u18"},
    "fce4cca6e9cc42f28df5a92293acb569":{
      "scriptId":"u19"},
    "ca5aebe1a1ca42a3acaeaee706ce1007":{
      "scriptId":"u20"},
    "2d72ce9fd425473a839911e84c6d1286":{
      "scriptId":"u21"},
    "91504088410d479fb5c9a90a36219e7c":{
      "scriptId":"u22"},
    "ea294d6024904b828c6a17e38ce4ee72":{
      "scriptId":"u23"},
    "d604b13157b3498fb1a99496618cb54b":{
      "scriptId":"u24"},
    "ba1cf3b37b184737baf635ece6abcbeb":{
      "scriptId":"u25"},
    "3e3f630f3591482db4dd822dcf37e0d6":{
      "scriptId":"u26"},
    "e65e5024100c4b599ffca922e266f189":{
      "scriptId":"u27"},
    "024c7b6c7ee345f9bf1a9a52e70dea43":{
      "scriptId":"u28"},
    "ccf5351c51434c41aa4a2be33b2b8bf6":{
      "scriptId":"u29"},
    "53214c10e57047c6b0232268cead1276":{
      "scriptId":"u30"},
    "8c36511335a5451b90f12359fb90d270":{
      "scriptId":"u31"}}});