$axure.loadCurrentPage({
  "url":"关于我们.html",
  "generationDate":new Date(1590810246529.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bf8b8f4994924b1ea5ec786917a11de9",
    "type":"Axure:Page",
    "name":"关于我们",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cb8b7c36be084e079ed2a42255066d88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":440,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bb5d3fb2cc34f5ebe3e062d2e571150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":440,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u0.png"}},
{
          "id":"e58b853b6085490b8657cc311da38fcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":50},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ff820f7236448da848dccbb909ebd9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":50},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"062d997155c34d4fa38a551155b69161",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":62},
            "size":{
              "width":130,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a5e38f8e4ef4fc382dbcd8c6fe420e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":62},
                "size":{
                  "width":130,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05bf4b197b374c1185121620357895fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":72},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4aab026a4243918e8f4791727e89f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":72},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"051f191a7efe445eb8ff8652572a3c75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":136},
            "size":{
              "width":300,
              "height":444}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b44b445c3dd4e15a1af7f306e6980ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":136},
                "size":{
                  "width":300,
                  "height":444}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "cb8b7c36be084e079ed2a42255066d88":{
      "scriptId":"u0"},
    "6bb5d3fb2cc34f5ebe3e062d2e571150":{
      "scriptId":"u1"},
    "e58b853b6085490b8657cc311da38fcc":{
      "scriptId":"u2"},
    "2ff820f7236448da848dccbb909ebd9e":{
      "scriptId":"u3"},
    "062d997155c34d4fa38a551155b69161":{
      "scriptId":"u4"},
    "5a5e38f8e4ef4fc382dbcd8c6fe420e2":{
      "scriptId":"u5"},
    "05bf4b197b374c1185121620357895fe":{
      "scriptId":"u6"},
    "1a4aab026a4243918e8f4791727e89f7":{
      "scriptId":"u7"},
    "051f191a7efe445eb8ff8652572a3c75":{
      "scriptId":"u8"},
    "3b44b445c3dd4e15a1af7f306e6980ac":{
      "scriptId":"u9"}}});