$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1590810246138.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b1e89a7e2ff943e7a298797f7a4e6fb5",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"88d9cdab04a94c338f76eb1cd853d0f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":60},
            "size":{
              "width":440,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c20fab09fb5f4ce4a8d006b22aca65d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":60},
                "size":{
                  "width":440,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u0.png"}},
{
          "id":"3c2f88027c594f6b89608a2c29edfeb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":70},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9a6ac46fdc24cbb8c88519adc8c8a9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":70},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"31bea1a4489645f18b46bfbdcb8cc072",
          "label":"login_info",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":77},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3945bc4c219e425a954947a1026dd17b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":77},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 注册页 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"注册页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9dfc0fbab1340e8abb1ac86f9e2daf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":120},
            "size":{
              "width":420,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61717af1b1ce43c48f797c40bd109a16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":120},
                "size":{
                  "width":420,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.png"}},
{
          "id":"ef10fe826ee141f5a7e81a8dd2c8f5f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":290},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d42f89a8f19c44ecb006598fbb6467b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":290},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 招聘信息详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"招聘信息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"3fa9672c6f36450f940361959543fb1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":390},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312e7bcf37244fd791aa055478c29a57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":390},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 招聘信息详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"招聘信息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"b33e8d9d13ad43248bc74b3aeb3f2895",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":590},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61401f573aa7447da4e4d452ec9d0b7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":590},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"a19a7aef6ab748d9a7ed1641d93fe7f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":260},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"408c052d6cbc44618390b9774a382e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":260},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"11650815d5164b3cbb75eb1def2b1874",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":260},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a88c81a512b421ebef5790465a614a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":260},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"20a1913636724ea88a5bccf962f1e000",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":260},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"443994b1f345419b832d7ba9f35d8c59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":260},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"f2f19d42132e4f8cadd0e9cc6f5e5372",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":490},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b53a074f564e6d85ac19b76af3df3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":490},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"89cebf6cd54445c084d8f9a85c7ce1c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":700},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53136e467b324695b5fae4ac9f26a064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":700},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"8f5c5f6d6172431e825e12717b90122b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":722},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a7ec5e8234743e09eb83f789f5883b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":722},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 首页 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b78f33da09604c2b9fe4cc24919904a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":722},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b2a761c8e56444daad594000fe8e770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":722},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 推荐首页 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"推荐首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e4261df8c104307ab5566e5d700ec08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":722},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15d71775396c428b8e7bdc4661a55975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":722},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90f787b8253d42068ac70aee60b8e151",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":60},
            "size":{
              "width":390,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e974dfde224611b3b3560524a6fd43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":60},
                "size":{
                  "width":390,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u30.png"}},
{
          "id":"77f916a78ac141eb884cc4cb04500a22",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":77},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be95628777ef44cb9087eace7fece57e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":660,
                  "y":77},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a800b04d1ed84132a350146af3b0f89e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":130},
            "size":{
              "width":300,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b735da55d59b4f719680ae1ee54c546f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":660,
                  "y":130},
                "size":{
                  "width":300,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"289e4955fcad4e3cb4b1987f2e8d9c50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":77},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4925d101dea148048568a1e389d0e486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":77},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7af94e2009a2454e8a6decb4710c04a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":260},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f05fe852b1342a3b33dd72b294c0bd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":260},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"930049eee5f84004a6348ba22e27beeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":260},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9afb005df254a1e9657815ec486da9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":260},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "88d9cdab04a94c338f76eb1cd853d0f1":{
      "scriptId":"u0"},
    "c20fab09fb5f4ce4a8d006b22aca65d0":{
      "scriptId":"u1"},
    "3c2f88027c594f6b89608a2c29edfeb8":{
      "scriptId":"u2"},
    "f9a6ac46fdc24cbb8c88519adc8c8a9f":{
      "scriptId":"u3"},
    "31bea1a4489645f18b46bfbdcb8cc072":{
      "scriptId":"u4"},
    "3945bc4c219e425a954947a1026dd17b":{
      "scriptId":"u5"},
    "d9dfc0fbab1340e8abb1ac86f9e2daf0":{
      "scriptId":"u6"},
    "61717af1b1ce43c48f797c40bd109a16":{
      "scriptId":"u7"},
    "ef10fe826ee141f5a7e81a8dd2c8f5f9":{
      "scriptId":"u8"},
    "d42f89a8f19c44ecb006598fbb6467b2":{
      "scriptId":"u9"},
    "3fa9672c6f36450f940361959543fb1e":{
      "scriptId":"u10"},
    "312e7bcf37244fd791aa055478c29a57":{
      "scriptId":"u11"},
    "b33e8d9d13ad43248bc74b3aeb3f2895":{
      "scriptId":"u12"},
    "61401f573aa7447da4e4d452ec9d0b7c":{
      "scriptId":"u13"},
    "a19a7aef6ab748d9a7ed1641d93fe7f1":{
      "scriptId":"u14"},
    "408c052d6cbc44618390b9774a382e67":{
      "scriptId":"u15"},
    "11650815d5164b3cbb75eb1def2b1874":{
      "scriptId":"u16"},
    "9a88c81a512b421ebef5790465a614a0":{
      "scriptId":"u17"},
    "20a1913636724ea88a5bccf962f1e000":{
      "scriptId":"u18"},
    "443994b1f345419b832d7ba9f35d8c59":{
      "scriptId":"u19"},
    "f2f19d42132e4f8cadd0e9cc6f5e5372":{
      "scriptId":"u20"},
    "87b53a074f564e6d85ac19b76af3df3b":{
      "scriptId":"u21"},
    "89cebf6cd54445c084d8f9a85c7ce1c7":{
      "scriptId":"u22"},
    "53136e467b324695b5fae4ac9f26a064":{
      "scriptId":"u23"},
    "8f5c5f6d6172431e825e12717b90122b":{
      "scriptId":"u24"},
    "4a7ec5e8234743e09eb83f789f5883b0":{
      "scriptId":"u25"},
    "b78f33da09604c2b9fe4cc24919904a6":{
      "scriptId":"u26"},
    "3b2a761c8e56444daad594000fe8e770":{
      "scriptId":"u27"},
    "8e4261df8c104307ab5566e5d700ec08":{
      "scriptId":"u28"},
    "15d71775396c428b8e7bdc4661a55975":{
      "scriptId":"u29"},
    "90f787b8253d42068ac70aee60b8e151":{
      "scriptId":"u30"},
    "e1e974dfde224611b3b3560524a6fd43":{
      "scriptId":"u31"},
    "77f916a78ac141eb884cc4cb04500a22":{
      "scriptId":"u32"},
    "be95628777ef44cb9087eace7fece57e":{
      "scriptId":"u33"},
    "a800b04d1ed84132a350146af3b0f89e":{
      "scriptId":"u34"},
    "b735da55d59b4f719680ae1ee54c546f":{
      "scriptId":"u35"},
    "289e4955fcad4e3cb4b1987f2e8d9c50":{
      "scriptId":"u36"},
    "4925d101dea148048568a1e389d0e486":{
      "scriptId":"u37"},
    "7af94e2009a2454e8a6decb4710c04a2":{
      "scriptId":"u38"},
    "1f05fe852b1342a3b33dd72b294c0bd6":{
      "scriptId":"u39"},
    "930049eee5f84004a6348ba22e27beeb":{
      "scriptId":"u40"},
    "e9afb005df254a1e9657815ec486da9f":{
      "scriptId":"u41"}}});