$axure.loadCurrentPage({
  "url":"我的简历.html",
  "generationDate":new Date(1590810246342.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"caa6b1d818394b5b91698c583c5d8703",
    "type":"Axure:Page",
    "name":"我的简历",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f962aad7bf61403f926d941226814b00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":440,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"346cb65ad65c46e2a87a582d8f116c0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":440,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u0.png"}},
{
          "id":"f28f174d0594403296ba69dc02cd4567",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":50},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffd365f1fedc4e119e7acfa2c8a4c663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":50},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"0f43f3f2bf2544a480e829464aef26d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":62},
            "size":{
              "width":130,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21d00f181dca46f1b8f46ab1c0963411",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":62},
                "size":{
                  "width":130,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d65b9727f12c4d0f826c65efb61231fd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":128},
            "size":{
              "width":373,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"f1a05286feb042e9bd1612ba41383db6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":134},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb92353caf3c4c6cb9cfbcf2d626acd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":134},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ac8c1982b384dc6bd2fb4f387088c9d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":178},
            "size":{
              "width":373,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"337d73500f994ba7a43614b05d9ac835",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":184},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b135d639421482aa7ea3801428f18ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":184},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2988f19b81874aa0ad5109fa9255f270",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":228},
            "size":{
              "width":373,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"efc2d2bf61c34bbbbea31e0564805b10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":234},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e1c5614f65c43b8be34ea39e50c37e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":234},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c00c34a7a34426992b2a3beecc149f6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":278},
            "size":{
              "width":373,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"e2cf9f62d4c54e3bbd476d50112e328f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":284},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"947421ccd9564f4a8ec6f73f4f98c302",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":284},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6ea9e4b39d34310a92a46bb84c4350c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":328},
            "size":{
              "width":373,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"909a9a76300446ff82130d85123c9684",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":334},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e59b80f0d44e33acbeffac6c2cda7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":334},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fc584f233e84a07a5a78f85b6cf2d88",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":378},
            "size":{
              "width":373,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"be7858ab513b47408922ea66f9b7723a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":384},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dab9081984a4df1be98c524c71762e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":384},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66612d876f194ad8970dd6c30f5ba032",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":428},
            "size":{
              "width":373,
              "height":222}},
          "adaptiveStyles":{
}},
{
          "id":"2568fb3e0c7748ab9771ae8c519b57e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":434},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724a702d34d44455b907d14076d5804c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":434},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b209568c753f4dcdae1ef3cd5e13d604",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":249.5,
              "y":680},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8fb0ce1bb9c0442a92d61d33fcff25e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":90},
            "size":{
              "width":80,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7387818a9271434b89a72a9d621e61df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":90},
                "size":{
                  "width":80,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的简历/u28.png"}},
{
          "id":"924c9d46819744329a5b5e90fcd7a47b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":72},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e517e137ebcb4ad3a0404516d357a183",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":72},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f962aad7bf61403f926d941226814b00":{
      "scriptId":"u0"},
    "346cb65ad65c46e2a87a582d8f116c0a":{
      "scriptId":"u1"},
    "f28f174d0594403296ba69dc02cd4567":{
      "scriptId":"u2"},
    "ffd365f1fedc4e119e7acfa2c8a4c663":{
      "scriptId":"u3"},
    "0f43f3f2bf2544a480e829464aef26d8":{
      "scriptId":"u4"},
    "21d00f181dca46f1b8f46ab1c0963411":{
      "scriptId":"u5"},
    "d65b9727f12c4d0f826c65efb61231fd":{
      "scriptId":"u6"},
    "f1a05286feb042e9bd1612ba41383db6":{
      "scriptId":"u7"},
    "eb92353caf3c4c6cb9cfbcf2d626acd4":{
      "scriptId":"u8"},
    "0ac8c1982b384dc6bd2fb4f387088c9d":{
      "scriptId":"u9"},
    "337d73500f994ba7a43614b05d9ac835":{
      "scriptId":"u10"},
    "2b135d639421482aa7ea3801428f18ed":{
      "scriptId":"u11"},
    "2988f19b81874aa0ad5109fa9255f270":{
      "scriptId":"u12"},
    "efc2d2bf61c34bbbbea31e0564805b10":{
      "scriptId":"u13"},
    "9e1c5614f65c43b8be34ea39e50c37e0":{
      "scriptId":"u14"},
    "2c00c34a7a34426992b2a3beecc149f6":{
      "scriptId":"u15"},
    "e2cf9f62d4c54e3bbd476d50112e328f":{
      "scriptId":"u16"},
    "947421ccd9564f4a8ec6f73f4f98c302":{
      "scriptId":"u17"},
    "f6ea9e4b39d34310a92a46bb84c4350c":{
      "scriptId":"u18"},
    "909a9a76300446ff82130d85123c9684":{
      "scriptId":"u19"},
    "c7e59b80f0d44e33acbeffac6c2cda7c":{
      "scriptId":"u20"},
    "8fc584f233e84a07a5a78f85b6cf2d88":{
      "scriptId":"u21"},
    "be7858ab513b47408922ea66f9b7723a":{
      "scriptId":"u22"},
    "7dab9081984a4df1be98c524c71762e5":{
      "scriptId":"u23"},
    "66612d876f194ad8970dd6c30f5ba032":{
      "scriptId":"u24"},
    "2568fb3e0c7748ab9771ae8c519b57e5":{
      "scriptId":"u25"},
    "724a702d34d44455b907d14076d5804c":{
      "scriptId":"u26"},
    "b209568c753f4dcdae1ef3cd5e13d604":{
      "scriptId":"u27"},
    "8fb0ce1bb9c0442a92d61d33fcff25e7":{
      "scriptId":"u28"},
    "7387818a9271434b89a72a9d621e61df":{
      "scriptId":"u29"},
    "924c9d46819744329a5b5e90fcd7a47b":{
      "scriptId":"u30"},
    "e517e137ebcb4ad3a0404516d357a183":{
      "scriptId":"u31"}}});