$axure.loadCurrentPage({
  "url":"招聘信息详情.html",
  "generationDate":new Date(1590810246198.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6485a13017e74d8d909a4f6421cff540",
    "type":"Axure:Page",
    "name":"招聘信息详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"087cc6730edc435d90786805d8b58ffe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":60},
            "size":{
              "width":440,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7afcd1f93b88408ba9f568a6cca03072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":60},
                "size":{
                  "width":440,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u0.png"}},
{
          "id":"9b921decaba24579bbaba38ff18d2f16",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":83},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d40d1858b254b30a10477bcf26000cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":83},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"163ae4ad1fae4c52a4a5d42dac359d18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":130},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88c57769210c4c1ba5290539d3884515",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":130},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff362cc14f0447d08333070614bbb16f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":190},
            "size":{
              "width":380,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a050c43df101460bb619b5425b62ea0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":190},
                "size":{
                  "width":380,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘信息详情/u6.png"}},
{
          "id":"e20a5975421a4167a916cd9c58ca095d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":156},
            "size":{
              "width":380,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c72ed0f249c14dc38f57f1903b3ac9b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":156},
                "size":{
                  "width":380,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘信息详情/u8.png"}},
{
          "id":"537b22b017af449aabe4ba2e2846b95e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":300},
            "size":{
              "width":380,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bb2ddaa69e44d7983dd2373eea3bb3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":300},
                "size":{
                  "width":380,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘信息详情/u10.png"}},
{
          "id":"3e5072fe8c464a8da49761ceb5dab53d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":700},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"538594ad96234d60baf4cfdf0ed1d03e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":700},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"ad1a3ea0faf14243af4c59abedfbcbca",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":717.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"17fc2a941ab9466ba411e39b7ea0dcdb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":717.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"49d641c12716442aa9afda8ff52fb72e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":670},
            "size":{
              "width":210,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"525a59f74d5140e9b9245c642e2071db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":670},
                "size":{
                  "width":210,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 我的简历 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"我的简历.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/招聘信息详情/u16.png"}},
{
          "id":"92d2bbfc160a4cd0bad2284b2f55c04b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":725.5},
            "size":{
              "width":120,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘信息详情/u18_line.png"}},
{
          "id":"98fe16cbf334496f8c1308ad2052dec0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":598,
              "y":680},
            "size":{
              "width":122,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9111354a4cee4210a7bfa570bfc06ac9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":598,
                  "y":680},
                "size":{
                  "width":122,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"300fad97c52446d4b3b0c6f27dd25ebd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":60},
            "size":{
              "width":352,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f33448ca602b4e289f9ae7b186d3e147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":60},
                "size":{
                  "width":352,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘信息详情/u21.png"}},
{
          "id":"b5bc690f0d1c47d388fd8da3852a6973",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"32px",
            "fontWeight":"700",
            "location":{
              "x":620,
              "y":73},
            "size":{
              "width":200,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce329de269574406af4d3d382ac76cd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"32px",
                "fontWeight":"700",
                "location":{
                  "x":620,
                  "y":73},
                "size":{
                  "width":200,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8be2f6690b147228e31914de4e54181",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":130},
            "size":{
              "width":300,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8d9bfcb62104ccf83fe84a4d171dd7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":130},
                "size":{
                  "width":300,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "087cc6730edc435d90786805d8b58ffe":{
      "scriptId":"u0"},
    "7afcd1f93b88408ba9f568a6cca03072":{
      "scriptId":"u1"},
    "9b921decaba24579bbaba38ff18d2f16":{
      "scriptId":"u2"},
    "8d40d1858b254b30a10477bcf26000cc":{
      "scriptId":"u3"},
    "163ae4ad1fae4c52a4a5d42dac359d18":{
      "scriptId":"u4"},
    "88c57769210c4c1ba5290539d3884515":{
      "scriptId":"u5"},
    "ff362cc14f0447d08333070614bbb16f":{
      "scriptId":"u6"},
    "a050c43df101460bb619b5425b62ea0f":{
      "scriptId":"u7"},
    "e20a5975421a4167a916cd9c58ca095d":{
      "scriptId":"u8"},
    "c72ed0f249c14dc38f57f1903b3ac9b9":{
      "scriptId":"u9"},
    "537b22b017af449aabe4ba2e2846b95e":{
      "scriptId":"u10"},
    "2bb2ddaa69e44d7983dd2373eea3bb3f":{
      "scriptId":"u11"},
    "3e5072fe8c464a8da49761ceb5dab53d":{
      "scriptId":"u12"},
    "538594ad96234d60baf4cfdf0ed1d03e":{
      "scriptId":"u13"},
    "ad1a3ea0faf14243af4c59abedfbcbca":{
      "scriptId":"u14"},
    "17fc2a941ab9466ba411e39b7ea0dcdb":{
      "scriptId":"u15"},
    "49d641c12716442aa9afda8ff52fb72e":{
      "scriptId":"u16"},
    "525a59f74d5140e9b9245c642e2071db":{
      "scriptId":"u17"},
    "92d2bbfc160a4cd0bad2284b2f55c04b":{
      "scriptId":"u18"},
    "98fe16cbf334496f8c1308ad2052dec0":{
      "scriptId":"u19"},
    "9111354a4cee4210a7bfa570bfc06ac9":{
      "scriptId":"u20"},
    "300fad97c52446d4b3b0c6f27dd25ebd":{
      "scriptId":"u21"},
    "f33448ca602b4e289f9ae7b186d3e147":{
      "scriptId":"u22"},
    "b5bc690f0d1c47d388fd8da3852a6973":{
      "scriptId":"u23"},
    "ce329de269574406af4d3d382ac76cd2":{
      "scriptId":"u24"},
    "a8be2f6690b147228e31914de4e54181":{
      "scriptId":"u25"},
    "a8d9bfcb62104ccf83fe84a4d171dd7a":{
      "scriptId":"u26"}}});