$axure.loadCurrentPage({
  "url":"推荐首页.html",
  "generationDate":new Date(1590810246244.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3203f2d98c924cbbbb32dcfe1633e8fc",
    "type":"Axure:Page",
    "name":"推荐首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e78263b2252742389d1e707654ec9e30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":160},
            "size":{
              "width":440,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a472846dd513456ebf7d968fd6b9a76d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":160},
                "size":{
                  "width":440,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u0.png"}},
{
          "id":"5839af3e1759425080a7448792232f5c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":590},
            "size":{
              "width":180,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"728cf9aa12af43009396498a302e1cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":590},
                "size":{
                  "width":180,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推荐首页/u2.png"}},
{
          "id":"c0c34e20991f4d82b255796ec8407b74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":590},
            "size":{
              "width":210,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe702be0577e4e528e0c1bc71be05ce6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":590},
                "size":{
                  "width":210,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0aa128fb79cd4b2f833eb372518cca22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":250},
            "size":{
              "width":180,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e9bcc73433f428fbf0c3815b596ea35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":250},
                "size":{
                  "width":180,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推荐首页/u2.png"}},
{
          "id":"17f50c18fd214150af919319c035e5e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":250},
            "size":{
              "width":210,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2b5668d03b54cb69d335333d95bf820",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":250},
                "size":{
                  "width":210,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51fe558d2bb24069a7b03a84dfb64759",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":415},
            "size":{
              "width":180,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30fdcac7e8704ce8a73b8a0507563091",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":415},
                "size":{
                  "width":180,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推荐首页/u2.png"}},
{
          "id":"72d5fc29e05e4039806257b488787f2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":415},
            "size":{
              "width":210,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3f5ad142724cd893e3e2b6ece79d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":415},
                "size":{
                  "width":210,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e3f74aa082e422bb132945933c1c732",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":800},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"727113e2e66b410ea074110777f17cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":800},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"fcb969304c3647468193f0cb7ce47776",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":822},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8366f41c2b4c48c89ba8acc94f44b7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":822},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 首页 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19927302cd354829b1412f988e30e338",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":822},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d306e0906bd04a15b01cce52bacfdcc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":822},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 推荐首页 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"推荐首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86da9b1929374e2bbe1bb3f07e2c196e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":822},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e5b6829eb0c455a8eeabf11178a5272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":822},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 个人中心 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb94e3fd14bc4c37a6ef9a931f97f927",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":100},
            "size":{
              "width":440,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"650df3c0f62b4b828df3585473f07ef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":100},
                "size":{
                  "width":440,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"27eb6ee98786498aa36951f895837715",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":112},
            "size":{
              "width":130,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36334af29bf44788bcd52995c86cd01d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":112},
                "size":{
                  "width":130,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f3e5a20a1804f95ace2405d257ca95d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":60},
            "size":{
              "width":352,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ff585ca522d4cc1a85efaf94f3b28b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":60},
                "size":{
                  "width":352,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘信息详情/u21.png"}},
{
          "id":"a404f7c138194c2c9769c5d65b95281a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"32px",
            "fontWeight":"700",
            "location":{
              "x":620,
              "y":73},
            "size":{
              "width":200,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2d7b3d1b90c4b4eaad14d8c3dc58384",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"32px",
                "fontWeight":"700",
                "location":{
                  "x":620,
                  "y":73},
                "size":{
                  "width":200,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c225433ac1e64df0915a454179f69b62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":130},
            "size":{
              "width":300,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd2acdb573e9486cba8a0c1f32a3deed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":130},
                "size":{
                  "width":300,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e78263b2252742389d1e707654ec9e30":{
      "scriptId":"u0"},
    "a472846dd513456ebf7d968fd6b9a76d":{
      "scriptId":"u1"},
    "5839af3e1759425080a7448792232f5c":{
      "scriptId":"u2"},
    "728cf9aa12af43009396498a302e1cf5":{
      "scriptId":"u3"},
    "c0c34e20991f4d82b255796ec8407b74":{
      "scriptId":"u4"},
    "fe702be0577e4e528e0c1bc71be05ce6":{
      "scriptId":"u5"},
    "0aa128fb79cd4b2f833eb372518cca22":{
      "scriptId":"u6"},
    "6e9bcc73433f428fbf0c3815b596ea35":{
      "scriptId":"u7"},
    "17f50c18fd214150af919319c035e5e3":{
      "scriptId":"u8"},
    "d2b5668d03b54cb69d335333d95bf820":{
      "scriptId":"u9"},
    "51fe558d2bb24069a7b03a84dfb64759":{
      "scriptId":"u10"},
    "30fdcac7e8704ce8a73b8a0507563091":{
      "scriptId":"u11"},
    "72d5fc29e05e4039806257b488787f2f":{
      "scriptId":"u12"},
    "1e3f5ad142724cd893e3e2b6ece79d35":{
      "scriptId":"u13"},
    "0e3f74aa082e422bb132945933c1c732":{
      "scriptId":"u14"},
    "727113e2e66b410ea074110777f17cdb":{
      "scriptId":"u15"},
    "fcb969304c3647468193f0cb7ce47776":{
      "scriptId":"u16"},
    "8366f41c2b4c48c89ba8acc94f44b7d5":{
      "scriptId":"u17"},
    "19927302cd354829b1412f988e30e338":{
      "scriptId":"u18"},
    "d306e0906bd04a15b01cce52bacfdcc9":{
      "scriptId":"u19"},
    "86da9b1929374e2bbe1bb3f07e2c196e":{
      "scriptId":"u20"},
    "2e5b6829eb0c455a8eeabf11178a5272":{
      "scriptId":"u21"},
    "cb94e3fd14bc4c37a6ef9a931f97f927":{
      "scriptId":"u22"},
    "650df3c0f62b4b828df3585473f07ef5":{
      "scriptId":"u23"},
    "27eb6ee98786498aa36951f895837715":{
      "scriptId":"u24"},
    "36334af29bf44788bcd52995c86cd01d":{
      "scriptId":"u25"},
    "4f3e5a20a1804f95ace2405d257ca95d":{
      "scriptId":"u26"},
    "0ff585ca522d4cc1a85efaf94f3b28b2":{
      "scriptId":"u27"},
    "a404f7c138194c2c9769c5d65b95281a":{
      "scriptId":"u28"},
    "b2d7b3d1b90c4b4eaad14d8c3dc58384":{
      "scriptId":"u29"},
    "c225433ac1e64df0915a454179f69b62":{
      "scriptId":"u30"},
    "dd2acdb573e9486cba8a0c1f32a3deed":{
      "scriptId":"u31"}}});